name: Feature request
description: Suggest a new feature or enhancement for the library
title: "[Feature Request]: <Context of the feature request>"
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Describe the problem or use case
      description: |
        Provide a detailed description of the problem or use case that the proposed feature aims to address.

        For example: "When using the Baklava in scenario X, I encountered issues with..."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Proposed solution
      description: |
        Describe your proposed solution or enhancement in detail.

        Explain how the new feature would work and how it would address the problem or improve the Baklava.
  - type: textarea
    id: alternatives-description
    attributes:
      label: Alternatives considered
      description: |
        If you have considered any alternative approaches or solutions, please describe them here.

        Explain why the proposed solution is preferred over the alternatives.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional technical context
      description: |
        Provide any additional technical context or considerations that may be relevant to the feature request.

        Include code snippets, relevant documentation, or any other information that can help the development team understand and evaluate the request better.
