name: New Component Definition
description: Use this template to define implementation
title: "[Component]: <Name of the component>"
labels: baklava-ds, enhancement
body:
  - type: input
    id: figma
    attributes:
      label: Figma Design Document
  - type: textarea
    id: implementation
    attributes:
      label: General Usage Example
      placeholder: |
        ```html
        <bl-button>Example</bl-button>
        ```
  - type: textarea
    id: rules
    attributes:
      label: Rules
      description: Put some rules about how this component should behave and be implemented
      placeholder: |
        * Rule 1
        * Rule 2
  - type: textarea
    id: attributes
    attributes:
      label: Attributes
      value: |
        | Attribute | Description | Default Value |
        | --------------- | --------------- | --------------- |
        | attr (`string`) | attr desc | - |
  - type: textarea
    id: slots
    attributes:
      label: Slots
      value: |
        | Name | Description | Default Content |
        | --------------- | --------------- | --------------- |
        | `default` slot | What to put | - |
  - type: textarea
    id: events
    attributes:
      label: Events
      value: |
        | Event | Description |
        | --------------- | --------------- |
        | `bl-{event-name}` | Event description |
  - type: textarea
    id: css
    attributes:
      label: CSS Custom Properties
      value: |
        | Property | Description | Default Value |
        | --------------- | --------------- | --------------- |
        | `--bl-name` | Property desc | - |
