name: Publish Storybook

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Deploy to GH Pages
        run: npm run deploy-storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
