name: 'Verify and Preview'

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  verify:
    uses: trendyol/baklava/.github/workflows/verify.yml@next
    secrets: inherit
  release-preview:
      runs-on: ubuntu-latest
      needs: verify
      steps:
        - name: Preview Release
          run: npx semantic-release@20 --dry-run -p '@semantic-release/commit-analyzer' -p '@semantic-release/release-notes-generator'
