name: 'Verify and Preview'

on:
  pull_request:
    branches:
      - next

permissions:
  pull-requests: read

jobs:
  verify:
    uses: trendyol/baklava/.github/workflows/verify.yml@next
    secrets: inherit
  chromatic:
    uses: trendyol/baklava/.github/workflows/publish-chromatic.yml@next
    needs: verify
