name: 'Verify and Preview'

on:
  pull_request:
    branches:
      - next

permissions:
  pull-requests: read

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    secrets: inherit
  chromatic:
    uses: ./.github/workflows/publish-chromatic.yml
    needs: verify
