name: 'Verify and Preview'

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  verify:
    uses: trendyol/baklava/.github/workflows/verify.yml@next
    secrets: inherit
