name: 'Verify and Preview'

on:
  pull_request:
    branches:
      - next
  workflow_dispatch: # Enables manual trigger for chromatic

permissions:
  pull-requests: read

jobs:
  verify:
    uses: trendyol/baklava/.github/workflows/verify.yml@next
    secrets: inherit

  chromatic:
    needs: verify
    uses: trendyol/baklava/.github/workflows/publish-chromatic.yml@next
    if: needs.verify.result == 'success' || github.event_name == 'workflow_dispatch' 
    # Runs automatically if verify succeeds, or manually when triggered
