name: Release

on:
  workflow_call:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Node env
        uses: actions/setup-node@v3
        with:
          node-version: 24.10.0
      - name: Install dependencies
        run: npm ci
      - name: Create env file with release config
        run: |
          touch .env
          echo RELEASE=true >> .env
      - name: Run build
        run: npm run build
      - name: Create build artifact
        uses: actions/upload-artifact@main
        with:
          name: build-output
          path: dist/
      - name: Publish
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
