name: 'Verify and Release Beta'

on:
  push:
    branches:
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  verify:
    uses: trendyol/baklava/.github/workflows/verify.yml@next
    secrets: inherit
  release:
    uses: trendyol/baklava/.github/workflows/release.yml@next
    needs: verify
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
  chromatic:
    uses: trendyol/baklava/.github/workflows/publish-chromatic.yml@next
    needs: verify
