name: 'Verify and Release'

on:
  push:
    branches:
      - main

jobs:
  verify:
    uses: trendyol/baklava/.github/workflows/verify.yml@next
    secrets: inherit
  publish:
    uses: trendyol/baklava/.github/workflows/publish-storybook.yml@next
    needs: verify
    secrets: inherit
  release:
    uses: trendyol/baklava/.github/workflows/release.yml@next
    needs: verify
    secrets: inherit
