name: 'Verify and Preview'

on:
  pull_request:
    branches: [ next ]
  push:
    branches: [ next ]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node 
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Prepare Build
        run: npm run prep
      - name: Run linter check 
        run: npm run lint
      - uses: microsoft/playwright-github-action@v1
      - name: Run tests
        run: npm run test
      - name: Build Grace
        run: npm run build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
